//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4016
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ForeignTradeModel", "FK_LINKMAN_CUSTOMER", "Customer", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LZL.ForeignTrade.DataEntity.Customer), "Linkman", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LZL.ForeignTrade.DataEntity.Linkman))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ForeignTradeModel", "FK_MEMORANDUM_CUSTOMER", "Customer", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LZL.ForeignTrade.DataEntity.Customer), "Memorandum", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LZL.ForeignTrade.DataEntity.Memorandum))]

// 原始文件名:
// 生成日期: 2009/6/30 20:56:08
namespace LZL.ForeignTrade.DataEntity
{
    
    /// <summary>
    /// 架构中不存在 Entities 的注释。
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“Entities”部分中的连接字符串初始化新 Entities 对象。
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 Customer 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Customer> Customer
        {
            get
            {
                if ((this._Customer == null))
                {
                    this._Customer = base.CreateQuery<Customer>("[Customer]");
                }
                return this._Customer;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Customer> _Customer;
        /// <summary>
        /// 架构中不存在 Linkman 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Linkman> Linkman
        {
            get
            {
                if ((this._Linkman == null))
                {
                    this._Linkman = base.CreateQuery<Linkman>("[Linkman]");
                }
                return this._Linkman;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Linkman> _Linkman;
        /// <summary>
        /// 架构中不存在 Memorandum 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Memorandum> Memorandum
        {
            get
            {
                if ((this._Memorandum == null))
                {
                    this._Memorandum = base.CreateQuery<Memorandum>("[Memorandum]");
                }
                return this._Memorandum;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Memorandum> _Memorandum;
        /// <summary>
        /// 架构中不存在 Customer 的注释。
        /// </summary>
        public void AddToCustomer(Customer customer)
        {
            base.AddObject("Customer", customer);
        }
        /// <summary>
        /// 架构中不存在 Linkman 的注释。
        /// </summary>
        public void AddToLinkman(Linkman linkman)
        {
            base.AddObject("Linkman", linkman);
        }
        /// <summary>
        /// 架构中不存在 Memorandum 的注释。
        /// </summary>
        public void AddToMemorandum(Memorandum memorandum)
        {
            base.AddObject("Memorandum", memorandum);
        }
    }
    /// <summary>
    /// 架构中不存在 ForeignTradeModel.Customer 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ForeignTradeModel", Name="Customer")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Customer : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Customer 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        /// <param name="nameCode">NameCode 的初始值。</param>
        /// <param name="isShare">IsShare 的初始值。</param>
        public static Customer CreateCustomer(global::System.Guid id, string nameCode, bool isShare)
        {
            Customer customer = new Customer();
            customer.ID = id;
            customer.NameCode = nameCode;
            customer.IsShare = isShare;
            return customer;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 NameCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCode
        {
            get
            {
                return this._NameCode;
            }
            set
            {
                this.OnNameCodeChanging(value);
                this.ReportPropertyChanging("NameCode");
                this._NameCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NameCode");
                this.OnNameCodeChanged();
            }
        }
        private string _NameCode;
        partial void OnNameCodeChanging(string value);
        partial void OnNameCodeChanged();
        /// <summary>
        /// 架构中不存在属性 NameCn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCn
        {
            get
            {
                return this._NameCn;
            }
            set
            {
                this.OnNameCnChanging(value);
                this.ReportPropertyChanging("NameCn");
                this._NameCn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NameCn");
                this.OnNameCnChanged();
            }
        }
        private string _NameCn;
        partial void OnNameCnChanging(string value);
        partial void OnNameCnChanged();
        /// <summary>
        /// 架构中不存在属性 NameEn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NameEn
        {
            get
            {
                return this._NameEn;
            }
            set
            {
                this.OnNameEnChanging(value);
                this.ReportPropertyChanging("NameEn");
                this._NameEn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NameEn");
                this.OnNameEnChanged();
            }
        }
        private string _NameEn;
        partial void OnNameEnChanging(string value);
        partial void OnNameEnChanged();
        /// <summary>
        /// 架构中不存在属性 Address 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// 架构中不存在属性 AddressEn 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressEn
        {
            get
            {
                return this._AddressEn;
            }
            set
            {
                this.OnAddressEnChanging(value);
                this.ReportPropertyChanging("AddressEn");
                this._AddressEn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("AddressEn");
                this.OnAddressEnChanged();
            }
        }
        private string _AddressEn;
        partial void OnAddressEnChanging(string value);
        partial void OnAddressEnChanged();
        /// <summary>
        /// 架构中不存在属性 Country 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this.ReportPropertyChanging("Country");
                this._Country = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Country");
                this.OnCountryChanged();
            }
        }
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// 架构中不存在属性 Province 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this._Province;
            }
            set
            {
                this.OnProvinceChanging(value);
                this.ReportPropertyChanging("Province");
                this._Province = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Province");
                this.OnProvinceChanged();
            }
        }
        private string _Province;
        partial void OnProvinceChanging(string value);
        partial void OnProvinceChanged();
        /// <summary>
        /// 架构中不存在属性 City 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// 架构中不存在属性 DakCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DakCode
        {
            get
            {
                return this._DakCode;
            }
            set
            {
                this.OnDakCodeChanging(value);
                this.ReportPropertyChanging("DakCode");
                this._DakCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DakCode");
                this.OnDakCodeChanged();
            }
        }
        private string _DakCode;
        partial void OnDakCodeChanging(string value);
        partial void OnDakCodeChanged();
        /// <summary>
        /// 架构中不存在属性 Phone 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// 架构中不存在属性 Fax 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this._Fax;
            }
            set
            {
                this.OnFaxChanging(value);
                this.ReportPropertyChanging("Fax");
                this._Fax = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Fax");
                this.OnFaxChanged();
            }
        }
        private string _Fax;
        partial void OnFaxChanging(string value);
        partial void OnFaxChanged();
        /// <summary>
        /// 架构中不存在属性 Internet 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Internet
        {
            get
            {
                return this._Internet;
            }
            set
            {
                this.OnInternetChanging(value);
                this.ReportPropertyChanging("Internet");
                this._Internet = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Internet");
                this.OnInternetChanged();
            }
        }
        private string _Internet;
        partial void OnInternetChanging(string value);
        partial void OnInternetChanged();
        /// <summary>
        /// 架构中不存在属性 Bank 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank
        {
            get
            {
                return this._Bank;
            }
            set
            {
                this.OnBankChanging(value);
                this.ReportPropertyChanging("Bank");
                this._Bank = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Bank");
                this.OnBankChanged();
            }
        }
        private string _Bank;
        partial void OnBankChanging(string value);
        partial void OnBankChanged();
        /// <summary>
        /// 架构中不存在属性 BankCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCode
        {
            get
            {
                return this._BankCode;
            }
            set
            {
                this.OnBankCodeChanging(value);
                this.ReportPropertyChanging("BankCode");
                this._BankCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BankCode");
                this.OnBankCodeChanged();
            }
        }
        private string _BankCode;
        partial void OnBankCodeChanging(string value);
        partial void OnBankCodeChanged();
        /// <summary>
        /// 架构中不存在属性 Note 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this.ReportPropertyChanging("Note");
                this._Note = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Note");
                this.OnNoteChanged();
            }
        }
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// 架构中不存在属性 TypeCode 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCode
        {
            get
            {
                return this._TypeCode;
            }
            set
            {
                this.OnTypeCodeChanging(value);
                this.ReportPropertyChanging("TypeCode");
                this._TypeCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TypeCode");
                this.OnTypeCodeChanged();
            }
        }
        private string _TypeCode;
        partial void OnTypeCodeChanging(string value);
        partial void OnTypeCodeChanged();
        /// <summary>
        /// 架构中不存在属性 IsShare 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsShare
        {
            get
            {
                return this._IsShare;
            }
            set
            {
                this.OnIsShareChanging(value);
                this.ReportPropertyChanging("IsShare");
                this._IsShare = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsShare");
                this.OnIsShareChanged();
            }
        }
        private bool _IsShare;
        partial void OnIsShareChanging(bool value);
        partial void OnIsShareChanged();
        /// <summary>
        /// 架构中不存在属性 CreateTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return this._CreateTime;
            }
            set
            {
                this.OnCreateTimeChanging(value);
                this.ReportPropertyChanging("CreateTime");
                this._CreateTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateTime");
                this.OnCreateTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
        /// <summary>
        /// 架构中不存在 Linkman 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ForeignTradeModel", "FK_LINKMAN_CUSTOMER", "Linkman")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Linkman> Linkman
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Linkman>("ForeignTradeModel.FK_LINKMAN_CUSTOMER", "Linkman");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Linkman>("ForeignTradeModel.FK_LINKMAN_CUSTOMER", "Linkman", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 Memorandum 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ForeignTradeModel", "FK_MEMORANDUM_CUSTOMER", "Memorandum")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Memorandum> Memorandum
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Memorandum>("ForeignTradeModel.FK_MEMORANDUM_CUSTOMER", "Memorandum");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Memorandum>("ForeignTradeModel.FK_MEMORANDUM_CUSTOMER", "Memorandum", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ForeignTradeModel.Linkman 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ForeignTradeModel", Name="Linkman")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Linkman : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Linkman 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Linkman CreateLinkman(global::System.Guid id)
        {
            Linkman linkman = new Linkman();
            linkman.ID = id;
            return linkman;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Job 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Job
        {
            get
            {
                return this._Job;
            }
            set
            {
                this.OnJobChanging(value);
                this.ReportPropertyChanging("Job");
                this._Job = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Job");
                this.OnJobChanged();
            }
        }
        private string _Job;
        partial void OnJobChanging(string value);
        partial void OnJobChanged();
        /// <summary>
        /// 架构中不存在属性 Phone 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// 架构中不存在属性 Fax 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this._Fax;
            }
            set
            {
                this.OnFaxChanging(value);
                this.ReportPropertyChanging("Fax");
                this._Fax = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Fax");
                this.OnFaxChanged();
            }
        }
        private string _Fax;
        partial void OnFaxChanging(string value);
        partial void OnFaxChanged();
        /// <summary>
        /// 架构中不存在属性 MobilePhone 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone
        {
            get
            {
                return this._MobilePhone;
            }
            set
            {
                this.OnMobilePhoneChanging(value);
                this.ReportPropertyChanging("MobilePhone");
                this._MobilePhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MobilePhone");
                this.OnMobilePhoneChanged();
            }
        }
        private string _MobilePhone;
        partial void OnMobilePhoneChanging(string value);
        partial void OnMobilePhoneChanged();
        /// <summary>
        /// 架构中不存在属性 Email 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// 架构中不存在属性 Note 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this.ReportPropertyChanging("Note");
                this._Note = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Note");
                this.OnNoteChanged();
            }
        }
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// 架构中不存在 Customer 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ForeignTradeModel", "FK_LINKMAN_CUSTOMER", "Customer")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Customer Customer
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("ForeignTradeModel.FK_LINKMAN_CUSTOMER", "Customer").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("ForeignTradeModel.FK_LINKMAN_CUSTOMER", "Customer").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Customer 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("ForeignTradeModel.FK_LINKMAN_CUSTOMER", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Customer>("ForeignTradeModel.FK_LINKMAN_CUSTOMER", "Customer", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 ForeignTradeModel.Memorandum 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ForeignTradeModel", Name="Memorandum")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Memorandum : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 Memorandum 对象。
        /// </summary>
        /// <param name="id">ID 的初始值。</param>
        public static Memorandum CreateMemorandum(global::System.Guid id)
        {
            Memorandum memorandum = new Memorandum();
            memorandum.ID = id;
            return memorandum;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Subject 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this.ReportPropertyChanging("Subject");
                this._Subject = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Subject");
                this.OnSubjectChanged();
            }
        }
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// 架构中不存在属性 Note 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this.ReportPropertyChanging("Note");
                this._Note = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Note");
                this.OnNoteChanged();
            }
        }
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// 架构中不存在属性 Date 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
        /// <summary>
        /// 架构中不存在 Customer 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ForeignTradeModel", "FK_MEMORANDUM_CUSTOMER", "Customer")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Customer Customer
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("ForeignTradeModel.FK_MEMORANDUM_CUSTOMER", "Customer").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("ForeignTradeModel.FK_MEMORANDUM_CUSTOMER", "Customer").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 Customer 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Customer>("ForeignTradeModel.FK_MEMORANDUM_CUSTOMER", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Customer>("ForeignTradeModel.FK_MEMORANDUM_CUSTOMER", "Customer", value);
                }
            }
        }
    }
}
